# For build.sh
mode_name="lts"
mode_desc="Select and use the packages for the linux-lts kernel"

# Kernel versions for LTS packages
pkgrel="1"
kernel_version="4.4.7-1"
kernel_version_major_next="4.5"

header=""
header() {
    header="\
# Maintainer: Jesus Alvarez <jeezusjr at gmail dot com>
#
# This PKGBUILD was generated by the archzfs build scripts located at
#
# http://github.com/archzfs/archzfs
#
# ! WARNING !
#
# The archzfs packages are kernel modules, so these PKGBUILDS will only work with the kernel package they target. In this
# case, the ${archzfs_package_group} packages will only work with the ${linux_target} package! To have a single PKGBUILD
# target many kernels would make for a cluttered PKGBUILD!
#
# If you have a custom kernel, you will need to change things in the PKGBUILDS. If you would like to have AUR or archzfs repo
# packages for your favorite kernel package built using the archzfs build tools, submit a request in the Issue tracker on the
# archzfs github page.
#
#"
}

update_lts_pkgbuilds() {
    pkg_list="spl-utils-lts spl-lts zfs-utils-lts zfs-lts"
    kernel_version_full=$(kernel_version_full ${lts_kernel_version})
    kernel_mod_path="${kernel_version_full}-ARCH"
    archzfs_package_group="archzfs-lts"
    spl_pkgver=${zol_version}_$(kernel_version_full_no_hyphen ${lts_kernel_version})
    zfs_pkgver=${spl_pkgver}
    spl_pkgrel=${lts_pkgrel}
    zfs_pkgrel=${lts_pkgrel}
    spl_utils_pkgname="spl-utils-lts"
    spl_pkgname="spl-lts"
    zfs_utils_pkgname="zfs-utils-lts"
    zfs_pkgname="zfs-lts"
    spl_utils_pkgbuild_path="packages/${mode}/spl-utils-lts"
    spl_pkgbuild_path="packages/${mode}/spl-lts"
    zfs_utils_pkgbuild_path="packages/${mode}/zfs-utils-lts"
    zfs_pkgbuild_path="packages/${mode}/zfs-lts"
    spl_src_target="http://archive.zfsonlinux.org/downloads/zfsonlinux/spl/spl-${zol_version}.tar.gz"
    zfs_src_target="http://archive.zfsonlinux.org/downloads/zfsonlinux/zfs/zfs-${zol_version}.tar.gz"
    spl_workdir="\${SRCDIR}/spl-${zol_version}"
    zfs_workdir="\${SRCDIR}/zfs-${zol_version}"
    linux_depends="linux>=${kernel_version_major} linux<${std_kernel_version_major_next}"
    linux_headers_depends="linux-headers>=${kernel_major_version}" "linux-headers<${kernel_major_version_next}"
    header
}
