# For build.sh
mode_name="std"
mode_desc="Select and use the packages for the default linux kernel"

# Kernel versions for default ZFS packages
pkgrel="1"
kernel_version="4.5.1-1"
kernel_version_next="4.6"

# Kernel version for GIT packages
pkgrel_git="${pkgrel}"
kernel_version_git="${kernel_version}"
kernel_version_git_next="${kernel_version_next}"
zfs_git_commit=""
spl_git_commit=""
zfs_git_url="https://github.com/zfsonlinux/zfs.git"
spl_git_url="https://github.com/zfsonlinux/spl.git"

# Archiso Configuration
pkgrel_archiso="1"
kernel_version_archiso="4.4.5"
kernel_version_archiso_next="4.5"

header="\
# Maintainer: Jesus Alvarez <jeezusjr at gmail dot com>
#
# This PKGBUILD was generated by the archzfs build scripts located at
#
# http://github.com/archzfs/archzfs
#
# ! WARNING !
#
# The archzfs packages are kernel modules, so these PKGBUILDS will only work with the kernel package they target. In this
# case, the archzfs-linux packages will only work with the default linux package! To have a single PKGBUILD target many
# kernels would make for a cluttered PKGBUILD!
#
# If you have a custom kernel, you will need to change things in the PKGBUILDS. If you would like to have AUR or archzfs repo
# packages for your favorite kernel package built using the archzfs build tools, submit a request in the Issue tracker on the
# archzfs github page.
#"

update_linux_pkgbuilds() {
    pkg_list="spl-utils-linux spl-linux zfs-utils-linux zfs-linux"
    kernel_version_full=$(kernel_version_full ${kernel_version})
    kernel_version_major=${kernel_version%-*}
    kernel_mod_path="${kernel_version_full}-ARCH"
    archzfs_package_group="archzfs-linux"
    spl_pkgver=${zol_version}_$(kernel_version_full_no_hyphen ${kernel_version})
    zfs_pkgver=${zol_version}_$(kernel_version_full_no_hyphen ${kernel_version})
    spl_pkgrel=${pkgrel}
    zfs_pkgrel=${pkgrel}
    spl_utils_pkgname="spl-utils-linux"
    spl_pkgname="spl-linux"
    zfs_utils_pkgname="zfs-utils-linux"
    zfs_pkgname="zfs-linux"
    # Paths are relative to build.sh
    spl_utils_pkgbuild_path="packages/linux/spl-utils-linux"
    spl_pkgbuild_path="packages/linux/spl-linux"
    zfs_utils_pkgbuild_path="packages/linux/zfs-utils-linux"
    zfs_pkgbuild_path="packages/linux/zfs-linux"
    spl_src_target="http://archive.zfsonlinux.org/downloads/zfsonlinux/spl/spl-${zol_version}.tar.gz"
    zfs_src_target="http://archive.zfsonlinux.org/downloads/zfsonlinux/zfs/zfs-${zol_version}.tar.gz"
    spl_workdir="\${srcdir}/spl-${zol_version}"
    zfs_workdir="\${srcdir}/zfs-${zol_version}"
    linux_depends="\"linux>=${kernel_version_major}\" \"linux<${kernel_version_next}\""
    linux_headers_depends="\"linux-headers>=${kernel_version_major}\" \"linux-headers<${kernel_version_next}\""
}

update_linux_git_pkgbuilds() {
    # CAUTION: Watch out for variable shadowing!
    pkg_list="spl-utils-linux-git spl-linux-git zfs-utils-linux-git zfs-linux-git"
    kernel_version=${kernel_version_git}
    kernel_version_full=$(kernel_version_full ${kernel_version_git})
    kernel_version_major=${kernel_version_git%-*}
    kernel_version_next=${kernel_version_git_next}
    kernel_mod_path="${kernel_version_full}-ARCH"
    archzfs_package_group="archzfs-linux-git"
    spl_pkgver=""
    zfs_pkgver=""
    spl_pkgrel=${pkgrel_git}
    zfs_pkgrel=${pkgrel_git}
    spl_utils_pkgname="spl-utils-linux-git"
    spl_pkgname="spl-linux-git"
    zfs_utils_pkgname="zfs-utils-linux-git"
    zfs_pkgname="zfs-linux-git"
    spl_utils_pkgbuild_path="packages/linux/spl-utils-linux-git"
    spl_pkgbuild_path="packages/linux/spl-linux-git"
    zfs_utils_pkgbuild_path="packages/linux/zfs-utils-linux-git"
    zfs_pkgbuild_path="packages/linux/zfs-linux-git"
    spl_src_target="git+${spl_git_url}"
    if [[ ${spl_git_commit} != "" ]]; then
        spl_src_target="git+${spl_git_url}#commit=${spl_git_commit}"
    fi
    spl_src_hash="SKIP"
    spl_makedepends='makedepends=("git")'
    zfs_src_target="git+${zfs_git_url}"
    if [[ ${zfs_git_commit} != "" ]]; then
        spl_src_target="git+${zfs_git_url}#commit=${zfs_git_commit}"
    fi
    zfs_src_hash="SKIP"
    zfs_makedepends='makedepends=("git")'
    spl_workdir="\${srcdir}/spl"
    zfs_workdir="\${srcdir}/zfs"
    linux_depends="\"linux>=${kernel_version_major}\" \"linux<${kernel_version_next}\""
    linux_headers_depends="\"linux-headers>=${kernel_version_major}\" \"linux-headers<${kernel_version_next}\""
    if have_command "update"; then
        git_check_repo
        git_calc_pkgver
    fi
}
