#!/bin/bash

cat << EOF > ${AZB_PKGBUILD_PATH}
# Maintainer: Jesus Alvarez <jeezusjr at gmail dot com>
#
# This PKGBUILD was generated by the archzfs build scripts located at
#
# http://github.com/archzfs/archzfs
#
EOF
